data:
  raw_path: "/home/nhattan05022003/coding/Personal/Basic_learning/CNN/Animals_project/data/raw"
  processed_path: "/home/nhattan05022003/coding/Personal/Basic_learning/CNN/Animals_project/data/processed"
  test_size: 0.2
  val_size: 0.1